### ISSUE TITLE
Snippets dont work in VSC

### ISSUE THREAD

**Issue by pronovaso** [tmarun/vscode-material-ui-snippets#1]
Hi.
I have Mac OS X 10.14 and VSC 1.27.1 and snippets are not working.

**Comment by tmarun** [comment]
sorry for the delay. I have not tested on Mac. Can you please post the error message which you get.

**Comment by pronovaso** [comment]
No error message. After install and restart VSC,VSC does not know any context with mui-modal-simple or something else.

**Comment by pronovaso** [comment]
I have some new info. When I typing mui in js,ts,jsx,tsx file does not work.
But I have Quoka new js file with testing some code and in this file mui work, but anywhere not.

**Comment by tmarun** [comment]
I found the issue. It is because vscode takes a considerable amount of time for loading the snippets.
You can follow the below steps
1. If you find "scanning" status in the status bar, then wait for that to complete. check the attached image
![mui-scanning](https://user-images.githubusercontent.com/28507759/67832610-33dde100-fb08-11e9-832f-561225a8fdfa.PNG)
2. The other option is find the keyword by checking the "details" tab of the extension and type the keyword and press tab. Check the attached image. 
    eg., type "mui-badges"  without quotes and press tab to get the snippets for the badges
![mui-key](https://user-images.githubusercontent.com/28507759/67832583-232d6b00-fb08-11e9-9d75-fa6c2b2166f9.PNG)
